# nume necesar (build)
build:
	gcc -o walsh walsh.c
	gcc -o statistics statistics.c
	gcc -o prinel prinel.c 
run-p1:      
	./walsh

run-p2:      # nume necesar
	./statistics
run-p3:      # nume necesar
	./prinel
run-p4:      # nume necesar

clean:
	rm -f walsh
	rm -f statistics
	rm -f prinel